In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import dask.dataframe as dd
from dask.distributed import Client

In [2]:
client = Client(n_workers=16)
client

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/bokeh/core.py:57: UserWarning:
Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
  warnings.warn('\n' + msg)

In [3]:
!pwd

/home/ec2-user/SageMaker/DS-Unit-3-Sprint-3-Big-Data/module1-aws-sagemaker

In [4]:
data_loc = 'instacart_2017_05_01/'

In [5]:
aisles = dd.read_csv(data_loc + 'aisles.csv', header=0, enforce=True)
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [6]:
depts = dd.read_csv(data_loc + 'departments.csv', header=0, enforce=True)
depts.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [7]:
order_products = dd.read_csv(data_loc + 'order_products*.csv', header=0)
order_products.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 4 entries, order_id to reordered
dtypes: int64(4)

In [8]:
order_products.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [9]:
products = dd.read_csv(data_loc + 'products.csv')
products.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 4 entries, product_id to department_id
dtypes: object(1), int64(3)

In [10]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [11]:
order_products = dd.merge(products, order_products)
order_products.head()

,product_id,product_name,aisle_id,department_id,order_id,add_to_cart_order,reordered
0,1,Chocolate Sandwich Cookies,61,19,1107,7,0
1,1,Chocolate Sandwich Cookies,61,19,5319,3,1
2,1,Chocolate Sandwich Cookies,61,19,7540,4,1
3,1,Chocolate Sandwich Cookies,61,19,9228,2,0
4,1,Chocolate Sandwich Cookies,61,19,9273,30,0

In [12]:
order_products = order_products.persist()

In [13]:
order_products_counts = order_products['product_name'].value_counts().compute()

In [14]:
order_products_counts[:100]

Banana                                                            491291
Bag of Organic Bananas                                            394930
Organic Strawberries                                              275577
Organic Baby Spinach                                              251705
Organic Hass Avocado                                              220877
Organic Avocado                                                   184224
Large Lemon                                                       160792
Strawberries                                                      149445
Limes                                                             146660
Organic Whole Milk                                                142813
Organic Raspberries                                               142603
Organic Yellow Onion                                              117716
Organic Garlic                                                    113936
Organic Zucchini                                                  109412
Organic Blueberries                                               105026
Cucumber Kirby                                                     99728
Organic Fuji Apple                                                 92889
Organic Lemon                                                      91251
Organic Grape Tomatoes                                             88078
Apple Honeycrisp Organic                                           87272
Seedless Red Grapes                                                86748
Organic Cucumber                                                   85005
Honeycrisp Apple                                                   83320
Organic Baby Carrots                                               80493
Sparkling Water Grapefruit                                         79245
Organic Half & Half                                                79006
Organic Large Extra Fancy Fuji Apple                               78056
Yellow Onions                                                      76929
Organic Baby Arugula                                               75752
Organic Gala Apples                                                75655
                                                                   ...
Organic Navel Orange                                               44701
Red Onion                                                          44477
Jalapeno Peppers                                                   44460
Uncured Genoa Salami                                               43261
Large Alfresco Eggs                                                42274
Roma Tomato                                                        42165
Organic Grade A Free Range Large Brown Eggs                        41812
Clementines, Bag                                                   41303
Orange Bell Pepper                                                 41052
Grape White/Green Seedless                                         40498
Organic Broccoli                                                   40373
Organic Black Beans                                                39577
100% Raw Coconut Water                                             39271
Organic Bartlett Pear                                              38686
2% Reduced Fat Milk                                                38631
Garlic                                                             38537
Shredded Parmesan                                                  37689
Granny Smith Apples                                                37566
Organic Carrot Bunch                                               37562
Soda                                                               37298
Unsalted Butter                                                    37102
Whole Milk                                                         36968
Organic Reduced Fat Milk                                           36869
Bartlett Pears                                                     36620
Unsweetened Original Almond Breeze Almond Milk                     36048
Organic Romaine Lettuce                                            36028
Organic Sticks Low Moisture Part Skim Mozzarella String Cheese     35551
Pure Irish Butter                                                  35384
Organic Broccoli Florets                                           34248
Sparkling Lemon Water                                              34211
Name: product_name, Length: 100, dtype: int64

In [22]:
depts.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [21]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [118]:
%%time
# Unfortunately, Dask does not support apply for columns,
# so we convert Dask Dataframe to Pandas Dataframe first.
grouped_df = order_products.groupby(['aisle_id'])[['reordered']] \
            .count() \
            .compute()

CPU times: user 226 ms, sys: 33.7 ms, total: 260 ms
Wall time: 1.57 s

In [119]:
grouped_df = grouped_df \
            .reset_index() \
            .rename(columns={'reordered': 'counts'}) \
            .sort_values(by='counts', ascending=False)
grouped_df.head()

     aisle_id   counts
23         24  3792661
82         83  3568630
122       123  1843806
119       120  1507583
20         21  1021462

In [120]:
grouped_df['%'] = grouped_df['counts'] / sum(grouped_df['counts']) * 100
grouped_df['cumulative %'] = grouped_df['%'].cumsum()

pd.set_option('display.max_rows', None)  # Unlimited rows
grouped_df.head(grouped_df.shape[0])

     aisle_id   counts          %  cumulative %
23         24  3792661  11.214551     11.214551
82         83  3568630  10.552112     21.766663
122       123  1843806   5.451966     27.218629
119       120  1507583   4.457785     31.676414
20         21  1021462   3.020370     34.696784
83         84   923659   2.731175     37.427959
114       115   878150   2.596609     40.024568
106       107   753739   2.228737     42.253305
90         91   664493   1.964845     44.218150
111       112   608469   1.799187     46.017337
30         31   599109   1.771510     47.788848
115       116   545107   1.611831     49.400679
36         37   521101   1.540848     50.941527
77         78   478430   1.414674     52.356201
2           3   473835   1.401087     53.757287
85         86   472009   1.395687     55.152975
95         96   412087   1.218504     56.371478
37         38   408520   1.207956     57.579435
91         92   395654   1.169913     58.749347
15         16   393793   1.164410     59.913757
120       121   393787   1.164392     61.078149
76         77   373816   1.105340     62.183489
66         67   370827   1.096501     63.279990
68         69   361573   1.069138     64.349129
97         98   348283   1.029841     65.378970
16         17   339780   1.004698     66.383668
52         53   330358   0.976838     67.360506
107       108   320827   0.948656     68.309162
116       117   319019   0.943310     69.252472
105       106   318468   0.941681     70.194153
44         45   312020   0.922615     71.116768
80         81   309716   0.915802     72.032569
87         88   301502   0.891514     72.924083
31         32   289488   0.855990     73.780073
58         59   282088   0.834108     74.614181
130       131   277935   0.821828     75.436009
35         36   264892   0.783261     76.219271
92         93   260621   0.770632     76.989903
93         94   258717   0.765002     77.754906
18         19   256086   0.757223     78.512129
53         54   255690   0.756052     79.268181
60         61   244045   0.721619     79.989799
51         52   242492   0.717027     80.706826
71         72   231792   0.685388     81.392214
8           9   228123   0.674539     82.066752
103       104   221371   0.654574     82.721326
25         26   215467   0.637116     83.358442
3           4   210604   0.622737     83.981179
128       129   203452   0.601589     84.582768
127       128   201650   0.596261     85.179029
49         50   182498   0.539630     85.718659
65         66   173614   0.513361     86.232019
22         23   170441   0.503978     86.735998
78         79   169879   0.502317     87.238314
129       130   164516   0.486459     87.724773
62         63   150323   0.444491     88.169264
34         35   134722   0.398361     88.567625
13         14   134597   0.397991     88.965616
113       114   124371   0.367754     89.333370
48         49   124045   0.366790     89.700159
42         43   118069   0.349119     90.049279
109       110   117521   0.347499     90.396777
50         51   113879   0.336730     90.733507
104       105   110847   0.327764     91.061272
63         64   108357   0.320402     91.381673
56         57   105762   0.312729     91.694402
41         42   104096   0.307802     92.002204
88         89   104050   0.307666     92.309871
12         13   103165   0.305049     92.614920
74         75    98990   0.292704     92.907624
73         74    98797   0.292134     93.199758
98         99    91193   0.269649     93.469408
1           2    86364   0.255370     93.724778
29         30    78495   0.232103     93.956880
99        100    77396   0.228853     94.185733
33         34    75083   0.222014     94.407747
47         48    75004   0.221780     94.629527
0           1    74864   0.221366     94.850893
121       122    74046   0.218947     95.069840
94         95    70287   0.207832     95.277672
28         29    69790   0.206363     95.484035
84         85    68852   0.203589     95.687624
24         25    66832   0.197616     95.885240
19         20    66819   0.197578     96.082818
40         41    66306   0.196061     96.278879
4           5    65415   0.193426     96.472305
26         27    50496   0.149312     96.621617
46         47    47028   0.139057     96.760674
110       111    45307   0.133969     96.894643
126       127    42905   0.126866     97.021509
57         58    41740   0.123421     97.144930
70         71    39420   0.116561     97.261492
11         12    38355   0.113412     97.374904
64         65    38211   0.112986     97.487890
5           6    38086   0.112617     97.600507
124       125    37053   0.109562     97.710070
27         28    36424   0.107702     97.817772
7           8    36372   0.107549     97.925321
39         40    35915   0.106197     98.031518
6           7    35391   0.104648     98.136166
59         60    33702   0.099654     98.235820
21         22    33482   0.099003     98.334823
61         62    31646   0.093574     98.428397
38         39    30726   0.090854     98.519251
123       124    29069   0.085954     98.605206
69         70    28078   0.083024     98.688230
10         11    27407   0.081040     98.769270
55         56    25714   0.076034     98.845304
96         97    24786   0.073290     98.918594
45         46    23626   0.069860     98.988453
89         90    22276   0.065868     99.054322
14         15    21840   0.064579     99.118900
100       101    20918   0.061853     99.180753
125       126    20801   0.061507     99.242260
118       119    20241   0.059851     99.302110
132       133    19580   0.057896     99.360007
86         87    18405   0.054422     99.414429
17         18    18093   0.053499     99.467928
67         68    17839   0.052748     99.520676
75         76    16620   0.049144     99.569820
79         80    15673   0.046344     99.616164
72         73    12915   0.038188     99.654352
32         33    12426   0.036743     99.691095
102       103    11706   0.034614     99.725708
133       134    11659   0.034475     99.760183
117       118    11411   0.033741     99.793924
54         55    10876   0.032159     99.826084
108       109    10698   0.031633     99.857717
9          10     9620   0.028445     99.886162
43         44     9522   0.028156     99.914318
101       102     8909   0.026343     99.940661
81         82     8466   0.025033     99.965694
131       132     6455   0.019087     99.984781
112       113     5147   0.015219    100.000000

In [121]:
grouped_df = grouped_df.merge(aisles.compute(), 
                              on='aisle_id')
grouped_df = grouped_df.nlargest(n=3000, columns='counts')

In [122]:
grouped_df.head(10)

   aisle_id   counts          %  cumulative %                          aisle
0        24  3792661  11.214551     11.214551                   fresh fruits
1        83  3568630  10.552112     21.766663               fresh vegetables
2       123  1843806   5.451966     27.218629     packaged vegetables fruits
3       120  1507583   4.457785     31.676414                         yogurt
4        21  1021462   3.020370     34.696784                packaged cheese
5        84   923659   2.731175     37.427959                           milk
6       115   878150   2.596609     40.024568  water seltzer sparkling water
7       107   753739   2.228737     42.253305                 chips pretzels
8        91   664493   1.964845     44.218150                soy lactosefree
9       112   608469   1.799187     46.017337                          bread

In [130]:
aisle_df = grouped_df \
            .set_index("aisle") \
            .drop("cumulative %", axis = 1)
aisle_df

                               aisle_id   counts          %
aisle
fresh fruits                         24  3792661  11.214551
fresh vegetables                     83  3568630  10.552112
packaged vegetables fruits          123  1843806   5.451966
yogurt                              120  1507583   4.457785
packaged cheese                      21  1021462   3.020370
milk                                 84   923659   2.731175
water seltzer sparkling water       115   878150   2.596609
chips pretzels                      107   753739   2.228737
soy lactosefree                      91   664493   1.964845
bread                               112   608469   1.799187
refrigerated                         31   599109   1.771510
frozen produce                      116   545107   1.611831
ice cream ice                        37   521101   1.540848
crackers                             78   478430   1.414674
energy granola bars                   3   473835   1.401087
eggs                                 86   472009   1.395687
lunch meat                           96   412087   1.218504
frozen meals                         38   408520   1.207956
baby food formula                    92   395654   1.169913
fresh herbs                          16   393793   1.164410
cereal                              121   393787   1.164392
soft drinks                          77   373816   1.105340
fresh dips tapenades                 67   370827   1.096501
soup broth bouillon                  69   361573   1.069138
juice nectars                        98   348283   1.029841
baking ingredients                   17   339780   1.004698
cream                                53   330358   0.976838
other creams cheeses                108   320827   0.948656
nuts seeds dried fruit              117   319019   0.943310
hot dogs bacon sausage              106   318468   0.941681
candy chocolate                      45   312020   0.922615
canned jarred vegetables             81   309716   0.915802
spreads                              88   301502   0.891514
packaged produce                     32   289488   0.855990
canned meals beans                   59   282088   0.834108
dry pasta                           131   277935   0.821828
butter                               36   264892   0.783261
breakfast bakery                     93   260621   0.770632
tea                                  94   258717   0.765002
oils vinegars                        19   256086   0.757223
paper goods                          54   255690   0.756052
cookies cakes                        61   244045   0.721619
frozen breakfast                     52   242492   0.717027
condiments                           72   231792   0.685388
pasta sauce                           9   228123   0.674539
spices seasonings                   104   221371   0.654574
coffee                               26   215467   0.637116
instant foods                         4   210604   0.622737
frozen appetizers sides             129   203452   0.601589
tortillas flat bread                128   201650   0.596261
fruit vegetable snacks               50   182498   0.539630
asian foods                          66   173614   0.513361
popcorn jerky                        23   170441   0.503978
frozen pizza                         79   169879   0.502317
hot cereal pancake mixes            130   164516   0.486459
grains rice dried goods              63   150323   0.444491
poultry counter                      35   134722   0.398361
tofu meat alternatives               14   134597   0.397991
cleaning products                   114   124371   0.367754
packaged poultry                     49   124045   0.366790
buns rolls                           43   118069   0.349119
pickled goods olives                110   117521   0.347499
preserved dips spreads               51   113879   0.336730
doughs gelatins bake mixes          105   110847   0.327764
energy sports drinks                 64   108357   0.320402
granola                              57   105762   0.312729
frozen vegan vegetarian              42   104096   0.307802
salad dressing toppings              89   104050   0.307666
prepared meals                       13   103165   0.305049
laundry                              75    98990   0.292704
dish detergents                      74    98797   0.292134
canned fruit applesauce              99    91193   0.269649
specialty cheeses                     2    86364   0.255370
latino foods                         30    78495   0.232103
missing                             100    77396   0.228853
frozen meat seafood                  34    75083   0.222014
breakfast bars pastries              48    75004   0.221780
prepared soups salads                 1    74864   0.221366
meat counter                        122    74046   0.218947
canned meat seafood                  95    70287   0.207832
honeys syrups nectars                29    69790   0.206363
food storage                         85    68852   0.203589
soap                                 25    66832   0.197616
oral hygiene                         20    66819   0.197578
cat food care                        41    66306   0.196061
marinades meat preparation            5    65415   0.193426
beers coolers                        27    50496   0.149312
vitamins supplements                 47    47028   0.139057
plates bowls cups flatware          111    45307   0.133969
body lotions soap                   127    42905   0.126866
frozen breads doughs                 58    41740   0.123421
refrigerated pudding desserts        71    39420   0.116561
fresh pasta                          12    38355   0.113412
protein meal replacements            65    38211   0.112986
other                                 6    38086   0.112617
trail mix snack mix                 125    37053   0.109562
red wines                            28    36424   0.107702
bakery desserts                       8    36372   0.107549
dog food care                        40    35915   0.106197
packaged meat                         7    35391   0.104648
trash bags liners                    60    33702   0.099654
hair care                            22    33482   0.099003
white wines                          62    31646   0.093574
seafood counter                      39    30726   0.090854
spirits                             124    29069   0.085954
digestion                            70    28078   0.083024
cold flu allergy                     11    27407   0.081040
diapers wipes                        56    25714   0.076034
baking supplies decor                97    24786   0.073290
mint gum                             46    23626   0.069860
cocoa drink mixes                    90    22276   0.065868
packaged seafood                     15    21840   0.064579
air fresheners candles              101    20918   0.061853
feminine care                       126    20801   0.061507
frozen dessert                      119    20241   0.059851
muscles joints pain relief          133    19580   0.057896
more household                       87    18405   0.054422
bulk dried fruits vegetables         18    18093   0.053499
bulk grains rice dried goods         68    17839   0.052748
indian foods                         76    16620   0.049144
deodorants                           80    15673   0.046344
facial care                          73    12915   0.038188
kosher foods                         33    12426   0.036743
ice cream toppings                  103    11706   0.034614
specialty wines champagnes          134    11659   0.034475
first aid                           118    11411   0.033741
shave needs                          55    10876   0.032159
skin care                           109    10698   0.031633
kitchen supplies                     10     9620   0.028445
eye ear care                         44     9522   0.028156
baby bath body care                 102     8909   0.026343
baby accessories                     82     8466   0.025033
beauty                              132     6455   0.019087
frozen juice                        113     5147   0.015219